### ISSUE TITLE
Make package compatible with league/oauth2-client v2.0

### ISSUE THREAD

**Issue by vkulov** [adam-paterson/oauth2-slack#13]
Do you have plans on releasing a version compatible with `league/oauth2-client` v2.0

We have v2.0 included in our app because it's required by `league/oauth2-linkedin` and `league/oauth2-google.`

By looking at the change list https://github.com/thephpleague/oauth2-client/blob/master/CHANGELOG.md it seems like the only breaking change is "Rename `getResponse()` to `getParsedResponse()`" used in `Slack.fetchAuthorizedUserDetails`

**Comment by adam-paterson** [comment]
@vkulov I'll have a look at implementing the new version at some point today. Thanks for using the library.

**Comment by pyrech** [comment]
Hi @adam-paterson :) Thanks for your oauth provider. :+1:

I also need a new release with league's v2.0 compatibility because of a PHP 7.1 deprecation thrown with league/oauth2-client in v1. Are you still working on it? Do you need some help to get the fix done? I can make a PR if you does not have time to do it.

Thanks!

**Comment by adam-paterson** [comment]
@pyrech I'm afraid I haven't had time to look into this yet. If you have the time feel free to submit a PR. All contributions are welcome.
